### PR TITLE
Add support for Koa 2.x

### PR DESCRIPTION
**Pull request by simplyianm**
Use promises rather than generators to support the new Koa flow.

### CODE REVIEW

**Comment by tejasmanohar** [comment]
Looks fine.

// cc @jonathanong

**Comment by jonathanong** [comment]
@tejasmanohar created a logging team and added you. i'm sure there are more logging middleware in this org but i don't have time to look right now

**Comment by tejasmanohar** [comment]
@simplyianm Everything you've done looks good, but we also need to update README + example.js before merging :)

**Comment by simplyianm** [comment]
Sounds good @tejasmanohar -- I'll write some docs

**Comment by tejasmanohar** [comment]
Looking good :)

**Comment by tejasmanohar** [comment]
https://github.com/koajs/logger/commit/6677c65d7f86789578efc2218524f53ee5f23c37

**Pull request closed without merging**
